apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: luminai-pv-claim-new
  namespace: student-m-puchner
  labels:
    app: luminai
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
