apiVersion: apps/v1
kind: Deployment
metadata:
  name: luminai
  namespace: student-m-puchner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luminai
  template:
    metadata:
      labels:
        app: luminai
    spec:
      containers:
        - name: luminai
          image: stenzm/luminai:latest
          envFrom:
            - configMapRef:
                name: luminai-configmap
          ports:
            - containerPort: 8080
          args: [ "while true; do sleep 30; done;" ]
---
apiVersion: v1
kind: Service
metadata:
  name: luminai-svc
  namespace: luminai
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: luminai
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: luminai
  namespace: luminai
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: luminai.stenz.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: luminai
                port:
                  number: 8080
  tls:
    - secretName: luminai-tls
      hosts:
        - luminai.stenz.dev
