apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescale-db  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescale-db
  template:
    metadata:
      labels:
        app: timescale-db
    spec:
      containers:
        - name: timescale-db
          image: timescale/timescaledb-ha:pg16 # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - secretRef:
                name: timescale-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: luminai
      volumes:
        - name: luminai
          persistentVolumeClaim:
            claimName: luminai-pv-claim-new