@startuml
'to group stuff
class group{
 name: string; PK
}

class sensor{
 name: string; PK
 group_name: number; FK
 type_name: number; FK
 unit: string;
}

class sensor_data{
 id: number; PK
 sensor_name: number; FK
 value: number;
 timestamp: number;
}

'producer or consumer...
class type{
 name: string; PK
}


group "1" -- "*" sensor
sensor "1" -- "*" sensor_data
type "1" -- "*" sensor
@enduml