name: LuminAi
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  GITHUB_USER: ${{ github.repository_owner }}
  IMAGE_NAME: "lumin-ai"

permissions:
  packages: write
  contents: read

jobs:
  backend:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm64]
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: build backend
        run: |
          cd LuminAi
          set -e
          rm -rf target
          ./mvnw -B clean package
          mkdir -p ./target/deploy
          cp ./target/quarkus-app/quarkus-run.jar ./target/deploy/
          docker build --tag lumin-ai --file ./src/main/docker/Dockerfile.jvm . --build-arg "DB_USER=${{ secrets.DB_USER }}" --build-arg "DB_PASS=${{ secrets.DB_PASS }}" --build-arg "DB_NAME=${{ secrets.DB_NAME }}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push backend docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

          # Tag and push ARM image
          if [ "${{ matrix.os }}" == "ubuntu-22.04-arm64" ]; then
            ARM_IMAGE_ID=$IMAGE_ID-arm
            docker tag $IMAGE_NAME $ARM_IMAGE_ID:$VERSION
            docker push $ARM_IMAGE_ID:$VERSION
          fi

