name: LuminAi
run-name:  Build Project for ${{ github.repository_owner }} as actor ${{ github.actor }} 🚀
on:
  workflow_dispatch:
    
  push:
    branches:
     - "main"

env:
  GITHUB_USER: ${{ github.repository_owner }}
  BACKEND_IMAGE_NAME: "ghcr.io/${{ github.repository_owner}}/backend:latest"
  FRONTEND_IMAGE_NAME: "ghcr.io/${{ github.repository_owner}}/frontend:latest"

permissions:
  packages: write
  contents: read

jobs:
  backend: 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: build backend
        run: |
          cd LuminAi
          ./build.sh
#        working-directory: .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: push backend docker image
        run: |
          IMAGE_ID=$(echo $BACKEND_IMAGE_NAME | tr '[A-Z]' '[a-z]')
          echo "tagging backend $IMGAE_ID"
          docker tag backend $IMGAE_ID
          docker push $IMGAE_ID
  done:
    runs-on: ubuntu-22.04
    needs:
      - backend
      #- frontend
    steps:
      - name: done
        run: |
          echo "# Demo Docker images pushed" >> $GITHUB_STEP_SUMMARY
          echo "## Steps to do" >> $GITHUB_STEP_SUMMARY
          echo "- do not forget to make **$BACKEND_IMAGE_NAME** and **$FRONTEND_IMAGE_NAME** public" >> $GITHUB_STEP_SUMMARY
          echo "- refresh the deployments in your cloud" >> $GITHUB_STEP_SUMMARY
