name: LuminAi
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  GITHUB_USER: ${{ github.repository_owner }}
  IMAGE_NAME: "lumin-ai"

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set docker image name env
        run: echo ::set-env name=DOCKER_IMAGE_NAME::pzalejko/quarkus-github-actions-demo
      -
        name: Set docker image tag env
        run: echo ::set-env name=DOCKER_TAG_VERSION::$(echo $GITHUB_RUN_NUMBER)
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./LuminAi
          file: ./src/main/docker/Dockerfile.jvw
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG_VERSION }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest
