name: LuminAi
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  GITHUB_USER: ${{ github.repository_owner }}
  IMAGE_NAME: "lumin-ai"

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: stenzm/luminai
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./LuminAi
          file: .LuminAi/src/main/docker/Dockerfile.jvw
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.run_number }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest
